application: hsibot
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: app.application

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: latest